[global]
log_level = "info"
[[chains]]
id = "velora-testnet-1"
rpc_addr = "http://127.0.0.1:26657"
grpc_addr = "http://127.0.0.1:9090"
account_prefix = "velora"
key_name = "relayer"
[[chains]]
id = "velora-testnet-2"
rpc_addr = "http://127.0.0.1:26658"
grpc_addr = "http://127.0.0.1:9091"
account_prefix = "velora"
key_name = "relayer"
